name: Actions

on:
  push

env:
  # Customize the CMake build type here (Release, Debug, RelWithDebInfo, etc.)
  BUILD_TYPE: Release

jobs:
  build:
    # The CMake configure and build commands are platform agnostic and should work equally well on Windows or Mac.
    # You can convert this to a matrix build if you need cross-platform coverage.
    # See: https://docs.github.com/en/free-pro-team@latest/actions/learn-github-actions/managing-complex-workflows#using-a-build-matrix
    runs-on: ${{ matrix.os }}
    strategy:
        matrix:
            os: [ubuntu-latest, windows-latest]

    steps:
    - uses: actions/checkout@v3

    - name: Configure CMake
      # Configure CMake in a 'build' subdirectory. `CMAKE_BUILD_TYPE` is only required if you are using a single-configuration generator such as make.
      # See https://cmake.org/cmake/help/latest/variable/CMAKE_BUILD_TYPE.html?highlight=cmake_build_type
      run: cmake -B ${{github.workspace}}/build -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}}

    - name: Build
      # Build your program with the given configuration
      run: cmake --build ${{github.workspace}}/build --config ${{env.BUILD_TYPE}}

    #- name: Test
    #  working-directory: ${{github.workspace}}/build
    #  # Execute tests defined by the CMake configuration.
    #  # See https://cmake.org/cmake/help/latest/manual/ctest.1.html for more detail
    #  run: ctest -C ${{env.BUILD_TYPE}}

    # Windows
    - name: windows-make-directory
      if: runner.os == 'Windows'
      shell: pwsh
      run: |
        mkdir -p ${{github.workspace}}\testing
        mkdir -p ${{github.workspace}}\testing\Windows

    - name: windows-test-package
      if: runner.os == 'Windows'
      shell: pwsh
      run: |
        Copy-Item -Path "${{github.workspace}}\bin\${{env.BUILD_TYPE}}\main_leetcode.exe" -Destination "${{github.workspace}}\testing\Windows"
        Copy-Item -Path "${{github.workspace}}\bin\${{env.BUILD_TYPE}}\*.lib" -Destination "${{github.workspace}}\testing\Windows"
        Copy-Item -Path "${{github.workspace}}\problems\*.json" -Destination "${{github.workspace}}\testing\Windows"

    - name: windows-test-upload
      if: runner.os == 'Windows'
      uses: actions/upload-artifact@v3
      with:
        name: win-leetcode-artifacts
        path: ${{github.workspace}}\testing\Windows